apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lattu-pvc
  namespace: default
spec:
  storageClassName: azurefile
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 25Gi