apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sachin-pvc
  namespace: default
spec:
  storageClassName: sachin-class
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi