apiVersion: v1
kind: Pod
metadata:
  name: dpod-multi-container
  namespace: default
spec:
  containers: 
  - image: nginx
    name: nginx-container
    ports: 
    - containerPort: 80
  - image: linuxserver/firefox
    name: firefox-container
    ports: 
    - containerPort: 3000    