trigger:
  branches: 
    include: 
    - main
  paths: 
    include: 
    - /environments/dev

pool: Default

stages:
  - stage: TerraformInitAndPlan
    displayName: Terraform Init and Plan
    jobs:
      - job: InitAndPlanJob
        displayName: Init and Plan Job
        steps:
        - task: TerraformTaskV4@4
          displayName: "Terraform Init"
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
            backendServiceArm: 'Ratan-SC'
            backendAzureRmResourceGroupName: 'pkrg'
            backendAzureRmStorageAccountName: 'merapehlastorage'
            backendAzureRmContainerName: 'newcant'
            backendAzureRmKey: 'jamesbond.terraform.tfstate'
        - task: TerraformTaskV4@4
          displayName: "Terraform Plan"
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
            environmentServiceNameAzureRM: 'Ratan-SC'
  - stage: TerraformApply
    displayName: Terraform Apply
    jobs: 
    - job: ManualApprovalJob
      displayName: Manual Approval Job
      pool: server
      steps:
      - task: ManualValidation@1
        inputs:
          notifyUsers: 'abc@abc.com'
          instructions: 'Please validate the plan and continue'
    - job: TerraformApply
      dependsOn: ManualApprovalJob
      displayName: Terraform Apply
      steps:
      - task: TerraformTaskV4@4
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
          backendServiceArm: 'Ratan-SC'
          backendAzureRmResourceGroupName: 'pkrg'
          backendAzureRmStorageAccountName: 'merapehlastorage'
          backendAzureRmContainerName: 'newcant'
          backendAzureRmKey: 'jamesbond.terraform.tfstate'
      - task: TerraformTaskV4@4
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
          environmentServiceNameAzureRM: 'Ratan-SC'
                 