trigger: none

pool: Default

stages:
  - stage: DEVTerraformInitAndPlan
    displayName: DEV Terraform Init and Plan
    jobs:
      - job: InitAndPlanJob
        displayName: Init and Plan Job
        steps:
        - task: TerraformTaskV4@4
          displayName: "Terraform Init"
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
            backendServiceArm: 'Ratan-SC'
            backendAzureRmResourceGroupName: 'pkrg'
            backendAzureRmStorageAccountName: 'merapehlastorage'
            backendAzureRmContainerName: 'newcant'
            backendAzureRmKey: 'jamesbond.terraform.tfstate'
        - task: TerraformTaskV4@4
          displayName: "Terraform Plan"
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
            environmentServiceNameAzureRM: 'Ratan-SC'

  - stage: QATerraformInitAndPlan
    displayName: QA Terraform Init and Plan
    jobs:
      - job: InitAndPlanJob
        displayName: Init and Plan Job
        steps:
        - task: TerraformTaskV4@4
          displayName: "Terraform Init"
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environments/qa'
            backendServiceArm: 'Ratan-SC'
            backendAzureRmResourceGroupName: 'pkrg'
            backendAzureRmStorageAccountName: 'merapehlastorage'
            backendAzureRmContainerName: 'newcant'
            backendAzureRmKey: 'qajamesbond.terraform.tfstate'
        - task: TerraformTaskV4@4
          displayName: "Terraform Plan"
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environments/qa'
            environmentServiceNameAzureRM: 'Ratan-SC'